name: Flutter
on: [push]
#  push:
#    branches:
#      - master
jobs:
  build:
    name: Build Web
    env:
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: cp lib/config/config.example.dart lib/config/config.dart
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email "binaretech@gmail.com" 
          git config --global user.name "Binary Software Technologies" 
          git add .
          git commit -am "release app"
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/ugma-today.git origin/master:master -f
