name: Flutter Web
on: [push]
#  push:
#    branches:
#      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.HEROKU_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email "binaretech@gmail.com" 
          git config --global user.name "Binary Software Technologies" 
          heroku git:remote -a ugma-today
          git add .
          git commit -am "release app"
          git push heroku master
